version: '3.4'

services:
    vendaval.api:
        image: ${DOCKER_REGISTRY-}vendavalapi
        build:
            context: .
            dockerfile: Vendaval.Api/Dockerfile
        depends_on:
            - redis
        environment:
            Redis__ConnectionString: "redis:6379"
        ports:
            - "8000:5000"
            - "8001:5001"

    redis: 
        image: "redis"
        container_name: "vendaval-redis"
        ports:
        - "6379:6379"