apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: vendaval-api
  name: vendaval.api
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 5000
    - name: "8001"
      port: 8001
      targetPort: 5001
  selector:
    io.kompose.service: vendaval-api
