apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: vendaval-api
  name: vendaval-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vendaval-api
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/vendaval-default: "true"
        io.kompose.service: vendaval-api
    spec:
      containers:
        - env:
            - name: Redis__ConnectionString
              value: redis:6379
          image: vendavalapi
          name: vendaval.api
          ports:
            - containerPort: 5000
              hostPort: 8000
              protocol: TCP
            - containerPort: 5001
              hostPort: 8001
              protocol: TCP
      restartPolicy: Always
